import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
const categories = new Set(["main", "sub", "status"]);
let ready;
async function ensureTable() {
  if (!ready) ready = prisma.$executeRawUnsafe("CREATE TABLE IF NOT EXISTS contract_base_options (id SERIAL PRIMARY KEY, category VARCHAR(20) NOT NULL, title TEXT NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(category, title))");
  return ready;
}
const categoryOf = (request) => new URL(request.url).searchParams.get("category") || "";
const validCategory = (category) => categories.has(category);
export async function GET(request) { try { await ensureTable(); const category = categoryOf(request); if (!validCategory(category)) return NextResponse.json({ error: "invalid_category" }, { status: 400 }); const items = await prisma.$queryRawUnsafe("SELECT id, title FROM contract_base_options WHERE category=$1 ORDER BY id ASC", category); return NextResponse.json({ items }); } catch (error) { console.error("contract_options_get_error", error); return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
export async function POST(request) { try { await ensureTable(); const category = categoryOf(request); const { title: rawTitle } = await request.json(); const title = String(rawTitle || "").trim(); if (!validCategory(category)) return NextResponse.json({ error: "invalid_category" }, { status: 400 }); if (!title) return NextResponse.json({ error: "title_required" }, { status: 400 }); const rows = await prisma.$queryRawUnsafe("INSERT INTO contract_base_options (category,title) VALUES ($1,$2) RETURNING id,title", category, title); return NextResponse.json({ item: rows[0] }, { status: 201 }); } catch (error) { if (error?.code === "23505") return NextResponse.json({ error: "title_exists" }, { status: 409 }); console.error("contract_options_post_error", error); return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
export async function PATCH(request) { try { await ensureTable(); const category = categoryOf(request); const { id: rawId, title: rawTitle } = await request.json(); const id = Number(rawId), title = String(rawTitle || "").trim(); if (!validCategory(category)) return NextResponse.json({ error: "invalid_category" }, { status: 400 }); if (!Number.isInteger(id) || id <= 0 || !title) return NextResponse.json({ error: "invalid_input" }, { status: 400 }); const rows = await prisma.$queryRawUnsafe("UPDATE contract_base_options SET title=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND category=$3 RETURNING id,title", title, id, category); if (!rows[0]) return NextResponse.json({ error: "not_found" }, { status: 404 }); return NextResponse.json({ item: rows[0] }); } catch (error) { if (error?.code === "23505") return NextResponse.json({ error: "title_exists" }, { status: 409 }); console.error("contract_options_patch_error", error); return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
export async function DELETE(request) { try { await ensureTable(); const category = categoryOf(request); const { ids } = await request.json(); const selectedIds = Array.from(new Set((Array.isArray(ids) ? ids : []).map(Number).filter((id) => Number.isInteger(id) && id > 0))); if (!validCategory(category)) return NextResponse.json({ error: "invalid_category" }, { status: 400 }); if (!selectedIds.length) return NextResponse.json({ error: "ids_required" }, { status: 400 }); await prisma.$executeRawUnsafe("DELETE FROM contract_base_options WHERE category=$1 AND id=ANY($2::int[])", category, selectedIds); return NextResponse.json({ ok: true }); } catch (error) { console.error("contract_options_delete_error", error); return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
