import { prisma } from "../../../lib/prisma";
import { isSessionExpired } from "../../../lib/security";

export const runtime = "nodejs";

const json = (data, status = 200) => Response.json(data, { status, headers: { "Cache-Control": "no-store" } });
const cookie = (request, name) => String(request.headers.get("cookie") || "").match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`))?.[1] || "";

class RouteError extends Error {
  constructor(code, status = 400) {
    super(code);
    this.code = code;
    this.status = status;
  }
}

async function userIdOf(request) {
  const sessionId = cookie(request, "ipm_session");
  const session = sessionId && await prisma.session.findUnique({ where: { id: sessionId } }).catch(() => null);
  if (session && !isSessionExpired(session)) return session.userId;
  if (process.env.NODE_ENV === "production") return null;
  const raw = request.headers.get("x-user-id") || cookie(request, "user_id");
  return /^\d+$/.test(raw) ? Number(raw) : 1;
}

function normalized(value = "") {
  return String(value).toLowerCase().replace(/ي/g, "ی").replace(/ك/g, "ک").replace(/\s+/g, " ").trim();
}

function normalizeDigits(value = "") {
  return String(value ?? "")
    .replace(/[\u06F0-\u06F9]/g, (digit) => String(digit.charCodeAt(0) - 0x06F0))
    .replace(/[\u0660-\u0669]/g, (digit) => String(digit.charCodeAt(0) - 0x0660));
}

function jalaliYearSuffix(date = new Date()) {
  const year = new Intl.DateTimeFormat("fa-IR-u-ca-persian", {
    year: "numeric",
    timeZone: "Asia/Tehran",
  }).format(date);
  return normalizeDigits(year).slice(-2);
}

function automaticSecretariatSequence(value, year) {
  const automatic = normalizeDigits(String(value || "").trim()).match(/^(\d{2})\/(\d{3})\/(\d{5})$/);
  return automatic && automatic[1] === year ? Number(automatic[3]) : null;
}

function plainSecretariatSequence(value) {
  const normalizedValue = normalizeDigits(String(value || "").trim());
  return /^\d{5}$/.test(normalizedValue) ? Number(normalizedValue) : null;
}

async function nextSharedSecretariatNumber(db, projectId) {
  const project = await db.project.findUnique({
    where: { id: Number(projectId) },
    select: { code: true },
  });
  const projectCode = normalizeDigits(String(project?.code || "").trim()).split(".")[0].match(/^\d{3}/)?.[0] || "";
  if (!projectCode) throw new RouteError("project_code_required", 400);

  const year = jalaliYearSuffix();
  const [letters, reports] = await Promise.all([
    db.letter.findMany({ select: { letterNo: true, secretariatNo: true } }),
    db.$queryRawUnsafe('SELECT report_number AS "reportNumber" FROM petty_cash_settlement_reports'),
  ]);
  const letterNumbers = letters.flatMap((letter) => [letter.letterNo, letter.secretariatNo]);
  const maxAutomaticLetterSequence = letterNumbers.reduce((max, value) => {
    const sequence = automaticSecretariatSequence(value, year);
    return Number.isFinite(sequence) && sequence > max ? sequence : max;
  }, 0);
  const maxPlainLetterSequence = letterNumbers.reduce((max, value) => {
    const sequence = plainSecretariatSequence(value);
    return Number.isFinite(sequence) && sequence > max ? sequence : max;
  }, 0);
  const reportAutomaticSequences = reports
    .map((report) => automaticSecretariatSequence(report.reportNumber, year))
    .filter(Number.isFinite);
  // A settlement report is always generated by this system. Its sequence can
  // therefore only continue the current registry, never jump to an unrelated
  // legacy plain number from imported documents.
  const reportSequenceLimit = Math.max(maxAutomaticLetterSequence, 9999) + reportAutomaticSequences.length;
  const maxReportSequence = reportAutomaticSequences.reduce(
    (max, sequence) => sequence <= reportSequenceLimit && sequence > max ? sequence : max,
    0,
  );
  const maxSequence = Math.max(maxAutomaticLetterSequence, maxReportSequence) || maxPlainLetterSequence;
  const nextSequence = maxSequence >= 10000 ? maxSequence + 1 : 10000;
  return `${year}/${projectCode}/${String(nextSequence).padStart(5, "0")}`;
}

async function repairOutlierSettlementReportNumbers(db) {
  const year = jalaliYearSuffix();
  const [letters, reports] = await Promise.all([
    db.letter.findMany({ select: { letterNo: true, secretariatNo: true } }),
    db.$queryRawUnsafe(`
      SELECT r.id,r.report_number AS "reportNumber",r.prepared_at AS "preparedAt",p.code AS "projectCode"
      FROM petty_cash_settlement_reports r
      INNER JOIN projects p ON p.id=r.project_id
      ORDER BY r.prepared_at ASC,r.id ASC
    `),
  ]);
  const letterNumbers = letters.flatMap((letter) => [letter.letterNo, letter.secretariatNo]);
  const maxAutomaticLetterSequence = letterNumbers.reduce((max, value) => {
    const sequence = automaticSecretariatSequence(value, year);
    return Number.isFinite(sequence) && sequence > max ? sequence : max;
  }, 0);
  const automaticReports = reports
    .map((report) => ({ ...report, sequence: automaticSecretariatSequence(report.reportNumber, year) }))
    .filter((report) => Number.isFinite(report.sequence));
  const validLimit = Math.max(maxAutomaticLetterSequence, 9999) + automaticReports.length;
  const validReports = automaticReports.filter((report) => report.sequence <= validLimit);
  const outliers = automaticReports.filter((report) => report.sequence > validLimit);
  let nextSequence = Math.max(maxAutomaticLetterSequence, ...validReports.map((report) => report.sequence), 9999);

  for (const report of outliers) {
    const projectCode = normalizeDigits(String(report.projectCode || "").trim()).split(".")[0].match(/^\d{3}/)?.[0];
    if (!projectCode) continue;
    nextSequence += 1;
    await db.$executeRawUnsafe(
      "UPDATE petty_cash_settlement_reports SET report_number=$1 WHERE id=$2",
      `${year}/${projectCode}/${String(nextSequence).padStart(5, "0")}`,
      Number(report.id),
    );
  }
}

function asAmount(value) {
  const digits = String(value ?? "")
    .replace(/[۰-۹]/g, (digit) => "۰۱۲۳۴۵۶۷۸۹".indexOf(digit))
    .replace(/[٠-٩]/g, (digit) => "٠١٢٣٤٥٦٧٨٩".indexOf(digit))
    .replace(/[^\d]/g, "");
  return digits ? BigInt(digits) : 0n;
}

function belongsToWorkflowUnit(stage, unit) {
  const name = normalized(unit?.name);
  const code = normalized(unit?.code);
  const values = `${name} ${code}`.replace(/\u200c/g, " ");
  if (stage === "planning") return /برنامه ریزی|کنترل پروژه|planning|project control/.test(values);
  if (stage === "project_manager") return /مدیریت پروژه|project management/.test(values);
  if (stage === "finance") return /مالی|حسابداری|finance|accounting/.test(values);
  if (stage === "management") return /مدیریت|management/.test(values) && !/مدیریت پروژه|project management|مالی|finance|accounting|کنترل پروژه/.test(values);
  return false;
}

let ready;
async function ensureTable() {
  if (!ready) ready = (async () => {
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS petty_cash_expenses (
        id SERIAL PRIMARY KEY,
        project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        expense_date VARCHAR(20) NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        budget_code VARCHAR(80) NOT NULL,
        amount BIGINT NOT NULL,
        created_by_id INTEGER NOT NULL,
        stage VARCHAR(32) NOT NULL DEFAULT 'planning',
        planning_status VARCHAR(20) NOT NULL DEFAULT 'pending',
        planning_by_id INTEGER,
        planning_at TIMESTAMP(3),
        project_manager_id INTEGER,
        project_manager_status VARCHAR(20) NOT NULL DEFAULT 'pending',
        project_manager_by_id INTEGER,
        project_manager_at TIMESTAMP(3),
        rejected_by_id INTEGER,
        created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    // CREATE TABLE IF NOT EXISTS does not add columns to installations that
    // already have an older version of this runtime-managed table.
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS rejected_by_id INTEGER");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS file_name VARCHAR(180)");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS file_url TEXT");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_expenses_project_idx ON petty_cash_expenses(project_id)");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_expenses_assignee_idx ON petty_cash_expenses(project_manager_id, stage)");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_expenses_creator_idx ON petty_cash_expenses(created_by_id)");
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS petty_cash_settlement_reports (
        id SERIAL PRIMARY KEY,
        report_number VARCHAR(40) NOT NULL UNIQUE,
        project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
        created_by_id INTEGER NOT NULL,
        prepared_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS petty_cash_settlement_report_items (
        id SERIAL PRIMARY KEY,
        report_id INTEGER NOT NULL REFERENCES petty_cash_settlement_reports(id) ON DELETE CASCADE,
        expense_id INTEGER NOT NULL UNIQUE REFERENCES petty_cash_expenses(id) ON DELETE RESTRICT,
        created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(report_id, expense_id)
      )
    `);
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_settlement_reports_project_idx ON petty_cash_settlement_reports(project_id)");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_settlement_report_items_report_idx ON petty_cash_settlement_report_items(report_id)");
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS petty_cash_expense_reports (
        id SERIAL PRIMARY KEY,
        report_name VARCHAR(180) NOT NULL,
        project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
        created_by_id INTEGER NOT NULL,
        submission_key UUID NOT NULL UNIQUE,
        created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS expense_report_id INTEGER REFERENCES petty_cash_expense_reports(id) ON DELETE RESTRICT");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_expense_reports_creator_idx ON petty_cash_expense_reports(created_by_id)");
    await prisma.$executeRawUnsafe("CREATE INDEX IF NOT EXISTS petty_cash_expenses_report_idx ON petty_cash_expenses(expense_report_id)");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expense_reports ADD COLUMN IF NOT EXISTS workflow_version INTEGER NOT NULL DEFAULT 1");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expense_reports ADD COLUMN IF NOT EXISTS review_history JSONB NOT NULL DEFAULT '[]'::jsonb");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expense_reports ADD COLUMN IF NOT EXISTS review_notes TEXT NOT NULL DEFAULT ''");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expense_reports ADD COLUMN IF NOT EXISTS initial_stage VARCHAR(32) NOT NULL DEFAULT 'planning'");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expense_reports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS return_stage VARCHAR(32)");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS review_status VARCHAR(20) NOT NULL DEFAULT 'pending'");
    await prisma.$executeRawUnsafe("ALTER TABLE petty_cash_expenses ADD COLUMN IF NOT EXISTS review_note TEXT NOT NULL DEFAULT ''");
  })();
  return ready;
}

async function workflowRoster() {
  const mappedRows = await prisma.$queryRawUnsafe(`
    SELECT DISTINCT urm."userId" AS "userId", unit.name AS "unitName", unit.code AS "unitCode"
    FROM "UserRoleMap" urm
    INNER JOIN "UnitRoleMap" unit_role ON unit_role."roleId" = urm."roleId"
    INNER JOIN "Unit" unit ON unit.id = unit_role."unitId"
  `).catch(() => []);
  const users = await prisma.user.findMany({
    where: { isActive: true },
    include: { units: { include: { unit: true } } },
    orderBy: { id: "asc" },
  });
  return Object.fromEntries(["planning", "project_manager", "finance", "management"].map((stage) => {
    const mappedIds = new Set(mappedRows.filter((row) => belongsToWorkflowUnit(stage, { name: row.unitName, code: row.unitCode })).map((row) => Number(row.userId)));
    return [stage, users.filter((user) => mappedIds.has(user.id) || (user.units || []).some((link) => belongsToWorkflowUnit(stage, link.unit)))
      .map((user) => ({ id: user.id, name: user.name, username: user.username, email: user.email }))];
  }));
}

async function workflowMembers(stage) { return (await workflowRoster())[stage] || []; }

function canReviewExpense(expense, userId, roster) {
  const stage = expense.stage;
  if (!roster[stage]?.some((user) => Number(user.id) === Number(userId))) return false;
  return stage !== "project_manager" || Number(expense.projectManagerId ?? expense.project_manager_id) === Number(userId);
}

async function expenseReportsFor(userId, roster, inbox = false) {
  const reports = await prisma.$queryRawUnsafe(`
    SELECT r.id,r.report_name AS "reportName",r.project_id AS "projectId",r.created_at AS "createdAt",
      r.created_by_id AS "createdById",r.workflow_version AS version,r.review_history AS "historyJson",r.review_notes AS "reviewNotes",r.updated_at AS "updatedAt",
      p.code AS "projectCode",p.name AS "projectName",creator.name AS "createdByName",creator.username AS "createdByUsername"
    FROM petty_cash_expense_reports r INNER JOIN projects p ON p.id=r.project_id
    LEFT JOIN "User" creator ON creator.id=r.created_by_id
    WHERE r.created_by_id=$1 OR EXISTS (
      SELECT 1 FROM petty_cash_expenses e WHERE e.expense_report_id=r.id AND (
        (e.stage='planning' AND $2::boolean) OR (e.stage='project_manager' AND e.project_manager_id=$1 AND $3::boolean)
        OR (e.stage='finance' AND $4::boolean) OR (e.stage='management' AND $5::boolean)))
      OR EXISTS (SELECT 1 FROM jsonb_array_elements(r.review_history) h WHERE (h->>'userId')::int=$1)
    ORDER BY r.created_at DESC,r.id DESC
  `, userId, roster.planning.some((u) => u.id === userId), roster.project_manager.some((u) => u.id === userId), roster.finance.some((u) => u.id === userId), roster.management.some((u) => u.id === userId));
  if (!reports.length) return [];
  const expenses = await prisma.$queryRawUnsafe(`
    SELECT e.id,e.expense_report_id AS "reportId",e.expense_date AS "expenseDate",e.description,e.budget_code AS "budgetCode",
      e.amount::text AS amount,e.file_name AS "fileName",e.file_url AS "fileUrl",e.stage,e.review_status AS "reviewStatus",e.review_note AS "reviewNote",
      e.project_manager_id AS "projectManagerId",manager.name AS "projectManagerName"
    FROM petty_cash_expenses e LEFT JOIN "User" manager ON manager.id=e.project_manager_id
    WHERE e.expense_report_id=ANY($1::int[]) ORDER BY e.id
  `, reports.map((r) => Number(r.id)));
  return reports.map((report) => {
    const items = expenses.filter((e) => Number(e.reportId) === Number(report.id)).map((e) => ({ ...e, id: Number(e.id), canAct: canReviewExpense(e, userId, roster) }));
    const canRevise = Number(report.createdById) === userId && items.some((e) => e.stage === "revision");
    return { ...report, id: Number(report.id), canAct: items.some((e) => e.canAct), canRevise, items, notificationTarget: "petty_cash_report", title: report.reportName, requestNumber: report.reportName };
  }).filter((report) => !inbox || report.canAct || report.canRevise);
}

async function isMember(userId, stage) {
  return (await workflowMembers(stage)).some((user) => Number(user.id) === Number(userId));
}

function itemFromRow(row) {
  return {
    id: Number(row.id), projectId: Number(row.projectId), projectCode: row.projectCode, projectName: row.projectName,
    expenseDate: row.expenseDate, description: row.description, budgetCode: row.budgetCode, amount: String(row.amount),
    fileName: row.fileName || null, fileUrl: row.fileUrl || null,
    stage: row.stage, planningStatus: row.planningStatus, planningById: row.planningById,
    planningByName: row.planningByName, planningByUsername: row.planningByUsername, planningAt: row.planningAt,
    projectManagerId: row.projectManagerId, projectManagerStatus: row.projectManagerStatus,
    projectManagerById: row.projectManagerById, projectManagerByName: row.projectManagerByName,
    projectManagerByUsername: row.projectManagerByUsername, projectManagerAt: row.projectManagerAt,
    createdById: row.createdById, createdByName: row.createdByName, createdByUsername: row.createdByUsername,
    settlementReportId: row.settlementReportId ? Number(row.settlementReportId) : null,
    settlementReportNumber: row.settlementReportNumber || null,
  };
}

function reportFromRow(row) {
  return {
    id: Number(row.id), reportNumber: row.reportNumber, projectId: Number(row.projectId),
    projectCode: row.projectCode, projectName: row.projectName, preparedAt: row.preparedAt,
    itemCount: Number(row.itemCount || 0), createdById: Number(row.createdById),
    createdByName: row.createdByName, createdByUsername: row.createdByUsername,
  };
}

export async function GET(request) {
  try {
    await ensureTable();
    const userId = await userIdOf(request);
    if (!userId) return json({ error: "unauthorized" }, 401);
    const reportUrl = new URL(request.url);
    if (reportUrl.searchParams.has("expenseReports")) {
      const roster = await workflowRoster();
      return json({ items: await expenseReportsFor(userId, roster) });
    }
    const reportInbox = reportUrl.searchParams.get("inbox") === "1" ? await expenseReportsFor(userId, await workflowRoster(), true) : [];
    await prisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock(91827461)");
      await repairOutlierSettlementReportNumbers(tx);
    });
    const url = new URL(request.url);
    const recipients = url.searchParams.get("recipients");
    if (recipients === "project_manager") return json({ users: await workflowMembers("project_manager") });

    if (url.searchParams.get("summary") === "received-details") {
      const projectId = Number(url.searchParams.get("projectId")) || 0;
      if (!projectId) return json({ error: "project_id_required" }, 400);

      // Keep this list tied to the exact inputs of the total displayed in the
      // "My petty cash" table: charged requests for this beneficiary and this
      // project only.  Do not expose other beneficiaries' payment details.
      const rows = await prisma.$queryRawUnsafe(`
        SELECT t.id,t.request_number AS "requestNumber",t.request_date AS "requestDate",
          t.charged_date AS "chargedDate",t.purpose,t.currency,
          COALESCE(t.charged_amount,0)::text AS "chargedAmount",
          COALESCE(t.cash_payment_amount,0)::text AS "cashPaymentAmount",
          t.cash_payment_currency AS "cashPaymentCurrency",t.cash_payment_method AS "cashPaymentMethod",
          COALESCE(t.credit_payment_amount,0)::text AS "creditPaymentAmount",
          t.credit_payment_currency AS "creditPaymentCurrency",t.credit_payment_description AS "creditPaymentDescription",
          p.code AS "projectCode",p.name AS "projectName",beneficiary.name AS "beneficiaryName",beneficiary.username AS "beneficiaryUsername"
        FROM tenkhah_requests t
        INNER JOIN projects p ON p.id=t.project_id
        LEFT JOIN "User" beneficiary ON beneficiary.id=COALESCE(t.beneficiary_user_id,t.created_by_id)
        WHERE COALESCE(t.beneficiary_user_id,t.created_by_id)=$1
          AND t.project_id=$2
          AND t.status='charged'
        ORDER BY t.charged_date DESC NULLS LAST,t.created_at DESC,t.id DESC
      `, userId, projectId);
      const items = rows.map((row) => ({ ...row, id: Number(row.id) }));
      const total = items.reduce((sum, item) => sum + BigInt(item.chargedAmount || "0"), 0n);
      return json({ items, total: total.toString() });
    }

    if (url.searchParams.get("summary") === "mine") {
      const rows = await prisma.$queryRawUnsafe(`
        WITH received AS (
          SELECT t.project_id AS "projectId",
            COALESCE(SUM(COALESCE(t.charged_amount, 0)), 0) AS "receivedAmount"
          FROM tenkhah_requests t
          WHERE COALESCE(t.beneficiary_user_id, t.created_by_id) = $1
            AND t.status = 'charged'
          GROUP BY t.project_id
        ), expenses AS (
          SELECT e.project_id AS "projectId",
            COALESCE(SUM(e.amount), 0) AS "registeredExpenses",
            COALESCE(SUM(e.amount) FILTER (
              WHERE e.stage = 'completed'
                AND e.project_manager_status = 'approved'
            ), 0) AS "approvedExpenses"
          FROM petty_cash_expenses e
          WHERE e.created_by_id = $1
          GROUP BY e.project_id
        ), totals AS (
          SELECT COALESCE(received."projectId", expenses."projectId") AS "projectId",
            COALESCE(received."receivedAmount", 0) AS "receivedAmount",
            COALESCE(expenses."registeredExpenses", 0) AS "registeredExpenses",
            COALESCE(expenses."approvedExpenses", 0) AS "approvedExpenses"
          FROM received
          FULL OUTER JOIN expenses ON expenses."projectId" = received."projectId"
        )
        SELECT totals."projectId", p.code AS "projectCode", p.name AS "projectName",
          totals."receivedAmount"::text AS "receivedAmount",
          totals."registeredExpenses"::text AS "registeredExpenses",
          (totals."receivedAmount" - totals."registeredExpenses")::text AS "registeredBalance",
          totals."approvedExpenses"::text AS "approvedExpenses",
          (totals."registeredExpenses" - totals."approvedExpenses")::text AS "unapprovedBalance"
        FROM totals
        INNER JOIN projects p ON p.id = totals."projectId"
        ORDER BY p.code ASC, p.name ASC
      `, userId);
      return json({ items: rows.map((row) => ({ ...row, projectId: Number(row.projectId) })) });
    }

    const [isPlanning, isProjectManager] = await Promise.all([isMember(userId, "planning"), isMember(userId, "project_manager")]);
    if (url.searchParams.get("reports") === "1") {
      const reportId = Number(url.searchParams.get("reportId")) || 0;
      const reportRows = await prisma.$queryRawUnsafe(`
        SELECT r.id,r.report_number AS "reportNumber",r.project_id AS "projectId",p.code AS "projectCode",p.name AS "projectName",r.prepared_at AS "preparedAt",
          r.created_by_id AS "createdById",creator.name AS "createdByName",creator.username AS "createdByUsername",COUNT(ri.id)::int AS "itemCount"
        FROM petty_cash_settlement_reports r
        INNER JOIN projects p ON p.id=r.project_id
        LEFT JOIN "User" creator ON creator.id=r.created_by_id
        LEFT JOIN petty_cash_settlement_report_items ri ON ri.report_id=r.id
        WHERE ($3::int=0 OR r.id=$3)
          AND (r.created_by_id=$1 OR $2::boolean OR EXISTS (
            SELECT 1 FROM petty_cash_settlement_report_items visible_ri
            INNER JOIN petty_cash_expenses visible_e ON visible_e.id=visible_ri.expense_id
            WHERE visible_ri.report_id=r.id AND visible_e.project_manager_id=$1
          ))
        GROUP BY r.id,p.code,p.name,creator.name,creator.username
        ORDER BY r.prepared_at DESC,r.id DESC
      `, userId, isPlanning, reportId);
      if (reportId && !reportRows.length) return json({ error: "report_not_found" }, 404);
      if (!reportId) return json({ items: reportRows.map(reportFromRow) });
      const expenseRows = await prisma.$queryRawUnsafe(`
        SELECT e.id,e.project_id AS "projectId",p.code AS "projectCode",p.name AS "projectName",e.expense_date AS "expenseDate",e.description,e.budget_code AS "budgetCode",e.amount::text AS amount,e.file_name AS "fileName",e.file_url AS "fileUrl",
          e.stage,e.planning_status AS "planningStatus",e.planning_by_id AS "planningById",planner.name AS "planningByName",planner.username AS "planningByUsername",e.planning_at AS "planningAt",
          e.project_manager_id AS "projectManagerId",e.project_manager_status AS "projectManagerStatus",e.project_manager_by_id AS "projectManagerById",manager.name AS "projectManagerByName",manager.username AS "projectManagerByUsername",e.project_manager_at AS "projectManagerAt",
          e.created_by_id AS "createdById",expense_creator.name AS "createdByName",expense_creator.username AS "createdByUsername",r.id AS "settlementReportId",r.report_number AS "settlementReportNumber"
        FROM petty_cash_settlement_report_items ri
        INNER JOIN petty_cash_settlement_reports r ON r.id=ri.report_id
        INNER JOIN petty_cash_expenses e ON e.id=ri.expense_id
        INNER JOIN projects p ON p.id=e.project_id
        LEFT JOIN "User" expense_creator ON expense_creator.id=e.created_by_id
        LEFT JOIN "User" planner ON planner.id=e.planning_by_id
        LEFT JOIN "User" manager ON manager.id=e.project_manager_by_id
        WHERE ri.report_id=$1
        ORDER BY ri.id ASC
      `, reportId);
      return json({ report: reportFromRow(reportRows[0]), items: expenseRows.map(itemFromRow) });
    }

    const inbox = url.searchParams.get("inbox") === "1";
    const expenseId = Number(url.searchParams.get("expenseId")) || 0;
    if (inbox) {
      const rows = await prisma.$queryRawUnsafe(`
        SELECT e.id,e.project_id AS "projectId",p.code AS "projectCode",p.name AS "projectName",e.expense_date AS "expenseDate",e.description,e.budget_code AS "budgetCode",e.amount::text AS amount,e.file_name AS "fileName",e.file_url AS "fileUrl",
          e.stage,e.planning_status AS "planningStatus",e.planning_by_id AS "planningById",planner.name AS "planningByName",planner.username AS "planningByUsername",e.planning_at AS "planningAt",
          e.project_manager_id AS "projectManagerId",e.project_manager_status AS "projectManagerStatus",e.project_manager_by_id AS "projectManagerById",manager.name AS "projectManagerByName",manager.username AS "projectManagerByUsername",e.project_manager_at AS "projectManagerAt",
          e.created_by_id AS "createdById",creator.name AS "createdByName",creator.username AS "createdByUsername",NULL::int AS "settlementReportId",NULL::text AS "settlementReportNumber"
        FROM petty_cash_expenses e
        INNER JOIN projects p ON p.id=e.project_id
        LEFT JOIN "User" creator ON creator.id=e.created_by_id
        LEFT JOIN "User" planner ON planner.id=e.planning_by_id
        LEFT JOIN "User" manager ON manager.id=e.project_manager_by_id
        WHERE ($1::int=0 OR e.id=$1)
          AND e.expense_report_id IS NULL
          AND ((e.stage='planning' AND e.planning_status='pending' AND $2::boolean)
            OR (e.stage='project_manager' AND e.project_manager_status='pending' AND e.project_manager_id=$3))
        ORDER BY e.created_at DESC,e.id DESC
      `, expenseId, isPlanning, userId);
      return json({ items: [...reportInbox, ...rows.map(itemFromRow)], viewer: { userId, isPlanning, isProjectManager } });
    }

    const projectId = Number(url.searchParams.get("projectId")) || 0;
    const rows = await prisma.$queryRawUnsafe(`
      SELECT e.id,e.project_id AS "projectId",p.code AS "projectCode",p.name AS "projectName",e.expense_date AS "expenseDate",e.description,e.budget_code AS "budgetCode",e.amount::text AS amount,e.file_name AS "fileName",e.file_url AS "fileUrl",
        e.stage,e.planning_status AS "planningStatus",e.planning_by_id AS "planningById",planner.name AS "planningByName",planner.username AS "planningByUsername",e.planning_at AS "planningAt",
        e.project_manager_id AS "projectManagerId",e.project_manager_status AS "projectManagerStatus",e.project_manager_by_id AS "projectManagerById",manager.name AS "projectManagerByName",manager.username AS "projectManagerByUsername",e.project_manager_at AS "projectManagerAt",
        e.created_by_id AS "createdById",creator.name AS "createdByName",creator.username AS "createdByUsername",report.id AS "settlementReportId",report.report_number AS "settlementReportNumber"
      FROM petty_cash_expenses e
      INNER JOIN projects p ON p.id=e.project_id
      LEFT JOIN "User" creator ON creator.id=e.created_by_id
      LEFT JOIN "User" planner ON planner.id=e.planning_by_id
      LEFT JOIN "User" manager ON manager.id=e.project_manager_by_id
      LEFT JOIN petty_cash_settlement_report_items report_item ON report_item.expense_id=e.id
      LEFT JOIN petty_cash_settlement_reports report ON report.id=report_item.report_id
      WHERE ($1::int=0 OR e.project_id=$1)
        AND (e.created_by_id=$2 OR e.project_manager_id=$2 OR $3::boolean)
      ORDER BY e.created_at DESC, e.id DESC
    `, projectId, userId, isPlanning);
    return json({ items: rows.map(itemFromRow), viewer: { userId, isPlanning, isProjectManager } });
  } catch (error) {
    console.error("petty_cash_expenses_get_error", error);
    return json({ error: "internal_error" }, 500);
  }
}

export async function POST(request) {
  try {
    await ensureTable();
    const userId = await userIdOf(request);
    if (!userId) return json({ error: "unauthorized" }, 401);
    const body = await request.json().catch(() => ({}));
    if (body.action === "create_expense_report") {
      const projectId = Number(body.projectId);
      const reportName = String(body.reportName || "").trim();
      const submissionKey = String(body.submissionKey || "");
      if (!Number.isInteger(projectId) || projectId <= 0 || !reportName || reportName.length > 180 ||
        !/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(submissionKey)) return json({ error: "invalid_report" }, 400);
      const entries = Array.isArray(body.items) ? body.items : [];
      if (!entries.length || entries.length > 500) return json({ error: "at_least_one_expense_required" }, 400);
      const expenses = entries.map((entry) => ({
        expenseDate: normalizeDigits(entry.expenseDate).trim(), description: String(entry.description || "").trim(),
        budgetCode: String(entry.budgetCode || "").trim(), amount: asAmount(entry.amount),
        fileName: String(entry.fileName || "").trim(), fileUrl: String(entry.fileUrl || "").trim(),
      }));
      if (expenses.some((expense) => !/^\d{4}[/-](0[1-9]|1[0-2])[/-](0[1-9]|[12]\d|3[01])$/.test(expense.expenseDate) ||
        !expense.description || !expense.budgetCode || expense.budgetCode.length > 80 || expense.amount <= 0n || expense.amount > 9223372036854775807n ||
        !expense.fileName || expense.fileName.length > 180 || !/^\/uploads\/petty-cash-expenses\/[a-f0-9-]+\.(jpg|jpeg|png|webp)$/.test(expense.fileUrl))) return json({ error: "required_expense_fields" }, 400);
      const roster = await workflowRoster();
      const initialStage = roster.finance.some((user) => user.id === userId) ? "management" : "planning";
      if (!roster[initialStage].length) return json({ error: "workflow_recipients_missing" }, 400);
      const report = await prisma.$transaction(async (tx) => {
        await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock($1)", userId);
        const existing = await tx.$queryRawUnsafe('SELECT id,created_by_id AS "createdById" FROM petty_cash_expense_reports WHERE submission_key=$1::uuid', submissionKey);
        if (existing.length) {
          if (Number(existing[0].createdById) !== userId) throw new RouteError("not_allowed", 403);
          return { id: Number(existing[0].id) };
        }
        const project = await tx.project.findFirst({ where: { id: projectId, isActive: true }, select: { id: true } });
        if (!project) throw new RouteError("active_project_not_found", 404);
        const codes = [...new Set(expenses.map((expense) => expense.budgetCode))];
        const budgets = await tx.costBreakdownItem.findMany({ where: { projectId, budgetCode: { in: codes } }, select: { budgetCode: true } });
        if (codes.some((code) => !budgets.some((budget) => budget.budgetCode === code))) throw new RouteError("budget_code_not_found", 400);
        const inserted = await tx.$queryRawUnsafe(`
          INSERT INTO petty_cash_expense_reports (report_name,project_id,created_by_id,submission_key,initial_stage,review_history)
          VALUES ($1,$2,$3,$4::uuid,$5,$6::jsonb) RETURNING id
        `, reportName, projectId, userId, submissionKey, initialStage, JSON.stringify([{ userId, action: "submitted", stage: initialStage, at: new Date().toISOString() }]));
        const reportId = Number(inserted[0].id);
        // One bulk insert keeps the complete report atomic, including every expense.
        await tx.$executeRawUnsafe(`
          INSERT INTO petty_cash_expenses (project_id,expense_date,description,budget_code,amount,created_by_id,file_name,file_url,expense_report_id,stage)
          SELECT $1,x."expenseDate",x.description,x."budgetCode",x.amount::bigint,$2,x."fileName",x."fileUrl",$3,$5
          FROM jsonb_to_recordset($4::jsonb) AS x("expenseDate" text,description text,"budgetCode" text,amount text,"fileName" text,"fileUrl" text)
        `, projectId, userId, reportId, JSON.stringify(expenses.map((expense) => ({ ...expense, amount: String(expense.amount) }))), initialStage);
        return { id: reportId, stage: initialStage };
      });
      return json({ ok: true, item: report }, 201);
    }
    if (body.action === "create_settlement_report") {
      const expenseIds = [...new Set((Array.isArray(body.expenseIds) ? body.expenseIds : []).map(Number).filter((id) => Number.isInteger(id) && id > 0))];
      if (!expenseIds.length) return json({ error: "at_least_one_expense_required" }, 400);
      const isPlanning = await isMember(userId, "planning");
      const report = await prisma.$transaction(async (tx) => {
        // This lock makes the registry number atomic across both letters and
        // settlement reports, even when they are registered simultaneously.
        await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock(91827461)");
        await repairOutlierSettlementReportNumbers(tx);
        const expenses = await tx.$queryRawUnsafe(`
          SELECT id,project_id AS "projectId",created_by_id AS "createdById",project_manager_id AS "projectManagerId",stage,project_manager_status AS "projectManagerStatus"
          FROM petty_cash_expenses
          WHERE id=ANY($1::int[])
          ORDER BY id
          FOR UPDATE
        `, expenseIds);
        if (expenses.length !== expenseIds.length) throw new RouteError("expense_not_found", 404);
        if (expenses.some((expense) => Number(expense.createdById) !== userId && Number(expense.projectManagerId) !== userId && !isPlanning)) throw new RouteError("not_allowed", 403);
        if (expenses.some((expense) => expense.stage !== "completed" || expense.projectManagerStatus !== "approved")) throw new RouteError("expenses_not_project_manager_approved", 400);
        const projectIds = new Set(expenses.map((expense) => Number(expense.projectId)));
        if (projectIds.size !== 1) throw new RouteError("expenses_must_have_same_project", 400);
        const grouped = await tx.$queryRawUnsafe("SELECT expense_id FROM petty_cash_settlement_report_items WHERE expense_id=ANY($1::int[])", expenseIds);
        if (grouped.length) throw new RouteError("expense_already_grouped", 409);
        const reportNumber = await nextSharedSecretariatNumber(tx, [...projectIds][0]);
        const inserted = await tx.$queryRawUnsafe(`
          INSERT INTO petty_cash_settlement_reports (report_number,project_id,created_by_id)
          VALUES ($1,$2,$3)
          RETURNING id,prepared_at AS "preparedAt"
        `, reportNumber, [...projectIds][0], userId);
        const reportId = Number(inserted[0].id);
        await tx.$executeRawUnsafe("INSERT INTO petty_cash_settlement_report_items (report_id,expense_id) SELECT $1,unnest($2::int[])", reportId, expenseIds);
        return { id: reportId, reportNumber, preparedAt: inserted[0].preparedAt, itemCount: expenseIds.length };
      });
      return json({ ok: true, item: report }, 201);
    }
    const projectId = Number(body.projectId);
    const expenseDate = String(body.expenseDate || "").trim();
    const description = String(body.description || "").trim();
    const budgetCode = String(body.budgetCode || "").trim();
    const amount = asAmount(body.amount);
    const fileName = String(body.fileName || "").trim().slice(0, 180) || null;
    const fileUrl = String(body.fileUrl || "").trim() || null;
    if (fileUrl && !/^\/uploads\/petty-cash-expenses\/[a-f0-9-]+\.[a-z0-9]+$/.test(fileUrl)) return json({ error: "invalid_attachment" }, 400);
    if (!projectId || !expenseDate || !description || !budgetCode || amount <= 0n) return json({ error: "invalid_input" }, 400);
    const [project, budget] = await Promise.all([
      prisma.project.findFirst({ where: { id: projectId, isActive: true }, select: { id: true } }),
      prisma.costBreakdownItem.findFirst({ where: { projectId, budgetCode }, select: { id: true } }),
    ]);
    if (!project) return json({ error: "active_project_not_found" }, 404);
    if (!budget) return json({ error: "budget_code_not_found" }, 400);
    const rows = await prisma.$queryRawUnsafe(`
      INSERT INTO petty_cash_expenses (project_id,expense_date,description,budget_code,amount,created_by_id,file_name,file_url)
      VALUES ($1,$2,$3,$4,$5::bigint,$6,$7,$8)
      RETURNING id
    `, projectId, expenseDate, description, budgetCode, String(amount), userId, fileName, fileUrl);
    return json({ ok: true, id: Number(rows[0].id) }, 201);
  } catch (error) {
    console.error("petty_cash_expenses_post_error", error);
    if (error instanceof RouteError) return json({ error: error.code }, error.status);
    if (error?.code === "P2002" || error?.code === "23505") return json({ error: "expense_already_grouped" }, 409);
    return json({ error: "internal_error" }, 500);
  }
}

export async function PATCH(request) {
  try {
    await ensureTable();
    const userId = await userIdOf(request);
    if (!userId) return json({ error: "unauthorized" }, 401);
    const body = await request.json().catch(() => ({}));
    const id = Number(body.id);
    if (body.action === "review_report") {
      const reportId = Number(body.reportId), version = Number(body.expectedVersion);
      const decision = String(body.decision || ""), note = String(body.note || "").trim();
      if (!Number.isInteger(reportId) || reportId <= 0 || !Number.isInteger(version) || version <= 0 || !["approve", "reject", "revision"].includes(decision) || note.length > 500) return json({ error: "invalid_input" }, 400);
      const rowDecisions = body.rowDecisions && typeof body.rowDecisions === "object" && !Array.isArray(body.rowDecisions) ? body.rowDecisions : {};
      if (Object.values(rowDecisions).some((value) => !["approve", "reject", "revision"].includes(value))) return json({ error: "invalid_input" }, 400);
      const roster = await workflowRoster();
      await prisma.$transaction(async (tx) => {
        const reports = await tx.$queryRawUnsafe("SELECT * FROM petty_cash_expense_reports WHERE id=$1 FOR UPDATE", reportId);
        const report = reports[0];
        if (!report) throw new RouteError("report_not_found", 404);
        if (Number(report.workflow_version) !== version) throw new RouteError("workflow_changed", 409);
        const expenses = await tx.$queryRawUnsafe("SELECT * FROM petty_cash_expenses WHERE expense_report_id=$1 ORDER BY id FOR UPDATE", reportId);
        const actionable = expenses.filter((expense) => canReviewExpense(expense, userId, roster));
        if (!actionable.length || Object.keys(rowDecisions).some((key) => !actionable.some((e) => String(e.id) === key))) throw new RouteError("not_allowed", 403);
        const choices = actionable.map((expense) => ({ expense, decision: decision === "approve" ? rowDecisions[expense.id] || decision : decision }));
        const projectManagerId = Number(body.projectManagerId) || null;
        if (choices.some((choice) => choice.expense.stage === "planning" && choice.decision === "approve") &&
          !roster.project_manager.some((user) => user.id === projectManagerId)) throw new RouteError("invalid_project_manager", 400);
        if (choices.some((choice) => choice.expense.stage === "project_manager" && choice.decision === "approve") && !roster.finance.length) throw new RouteError("workflow_recipients_missing", 400);
        const changes = [];
        for (const choice of choices) {
          const expense = choice.expense;
          const nextStage = choice.decision === "reject" ? "rejected" : choice.decision === "revision" ? "revision"
            : expense.stage === "planning" ? "project_manager" : expense.stage === "project_manager" ? "finance" : "completed";
          const status = choice.decision === "approve" ? "approved" : choice.decision === "reject" ? "rejected" : "revision";
          await tx.$executeRawUnsafe(`
            UPDATE petty_cash_expenses SET stage=$1,review_status=$2::text,review_note=$3,
              return_stage=CASE WHEN $2='revision' THEN stage ELSE NULL END,
              project_manager_id=CASE WHEN stage='planning' AND $2='approved' THEN $4::int ELSE project_manager_id END,
              planning_status=CASE WHEN stage='planning' THEN $2 ELSE planning_status END,
              planning_by_id=CASE WHEN stage='planning' THEN $5::int ELSE planning_by_id END,
              planning_at=CASE WHEN stage='planning' THEN CURRENT_TIMESTAMP ELSE planning_at END,
              project_manager_status=CASE WHEN stage='project_manager' THEN $2 ELSE project_manager_status END,
              project_manager_by_id=CASE WHEN stage='project_manager' THEN $5::int ELSE project_manager_by_id END,
              project_manager_at=CASE WHEN stage='project_manager' THEN CURRENT_TIMESTAMP ELSE project_manager_at END,
              rejected_by_id=CASE WHEN $2='rejected' THEN $5::int ELSE rejected_by_id END,updated_at=CURRENT_TIMESTAMP
            WHERE id=$6
          `, nextStage, status, note, projectManagerId, userId, Number(expense.id));
          changes.push({ id: Number(expense.id), fromStage: expense.stage, toStage: nextStage, decision: choice.decision });
        }
        await tx.$executeRawUnsafe(`UPDATE petty_cash_expense_reports SET workflow_version=workflow_version+1,
          review_history=review_history || $1::jsonb,review_notes=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3`,
        JSON.stringify([{ userId, action: decision, note, changes, at: new Date().toISOString() }]), note, reportId);
      });
      return json({ ok: true });
    }
    if (body.action === "resubmit_report") {
      const reportId = Number(body.reportId), version = Number(body.expectedVersion);
      const reportName = String(body.reportName || "").trim();
      const entries = Array.isArray(body.items) ? body.items : [];
      if (!Number.isInteger(reportId) || reportId <= 0 || !Number.isInteger(version) || !reportName || reportName.length > 180 || !entries.length || entries.length > 500) return json({ error: "invalid_report" }, 400);
      const normalizedEntries = entries.map((entry) => ({ id: Number(entry.id) || 0, expenseDate: normalizeDigits(entry.expenseDate).trim(),
        description: String(entry.description || "").trim(), budgetCode: String(entry.budgetCode || "").trim(), amount: asAmount(entry.amount),
        fileName: String(entry.fileName || "").trim(), fileUrl: String(entry.fileUrl || "").trim() }));
      if (normalizedEntries.some((entry) => !/^\d{4}[/-](0[1-9]|1[0-2])[/-](0[1-9]|[12]\d|3[01])$/.test(entry.expenseDate) || !entry.description || !entry.budgetCode || entry.budgetCode.length > 80 ||
        entry.amount <= 0n || entry.amount > 9223372036854775807n || !entry.fileName || entry.fileName.length > 180 || !/^\/uploads\/petty-cash-expenses\/[a-f0-9-]+\.(jpg|jpeg|png|webp)$/.test(entry.fileUrl))) return json({ error: "required_expense_fields" }, 400);
      const roster = await workflowRoster();
      await prisma.$transaction(async (tx) => {
        const reports = await tx.$queryRawUnsafe("SELECT * FROM petty_cash_expense_reports WHERE id=$1 FOR UPDATE", reportId);
        const report = reports[0];
        if (!report || Number(report.created_by_id) !== userId) throw new RouteError("not_allowed", 403);
        if (Number(report.workflow_version) !== version) throw new RouteError("workflow_changed", 409);
        const existing = await tx.$queryRawUnsafe("SELECT * FROM petty_cash_expenses WHERE expense_report_id=$1 ORDER BY id FOR UPDATE", reportId);
        if (!existing.some((e) => e.stage === "revision")) throw new RouteError("not_allowed", 403);
        if (new Set(normalizedEntries.filter((e) => e.id).map((e) => e.id)).size !== normalizedEntries.filter((e) => e.id).length ||
          existing.some((e) => !normalizedEntries.some((entry) => entry.id === Number(e.id))) || normalizedEntries.some((entry) => entry.id && !existing.some((e) => Number(e.id) === entry.id))) throw new RouteError("invalid_input", 400);
        const codes = [...new Set(normalizedEntries.map((entry) => entry.budgetCode))];
        const budgets = await tx.costBreakdownItem.findMany({ where: { projectId: Number(report.project_id), budgetCode: { in: codes } }, select: { budgetCode: true } });
        if (codes.some((code) => !budgets.some((budget) => budget.budgetCode === code))) throw new RouteError("budget_code_not_found", 400);
        const changes = [];
        for (const entry of normalizedEntries) {
          const previous = existing.find((e) => Number(e.id) === entry.id);
          if (previous && previous.stage !== "revision") {
            if (entry.expenseDate !== previous.expense_date || entry.description !== previous.description || entry.budgetCode !== previous.budget_code || String(entry.amount) !== String(previous.amount) || entry.fileUrl !== previous.file_url || entry.fileName !== previous.file_name) throw new RouteError("not_allowed", 403);
            continue;
          }
          const stage = previous?.return_stage || report.initial_stage;
          if (!["planning", "project_manager", "finance", "management"].includes(stage)) throw new RouteError("invalid_input", 400);
          if (!roster[stage].length) throw new RouteError("workflow_recipients_missing", 400);
          if (stage === "project_manager" && !roster.project_manager.some((u) => u.id === Number(previous?.project_manager_id))) throw new RouteError("invalid_project_manager", 400);
          if (previous) {
            await tx.$executeRawUnsafe(`UPDATE petty_cash_expenses SET expense_date=$1,description=$2,budget_code=$3,amount=$4::bigint,file_name=$5,file_url=$6,
              stage=$7,return_stage=NULL,review_status='pending',review_note='',updated_at=CURRENT_TIMESTAMP WHERE id=$8`,
            entry.expenseDate, entry.description, entry.budgetCode, String(entry.amount), entry.fileName, entry.fileUrl, stage, entry.id);
          } else {
            await tx.$executeRawUnsafe(`INSERT INTO petty_cash_expenses (project_id,expense_date,description,budget_code,amount,created_by_id,file_name,file_url,expense_report_id,stage)
              VALUES ($1,$2,$3,$4,$5::bigint,$6,$7,$8,$9,$10)`, Number(report.project_id), entry.expenseDate, entry.description, entry.budgetCode, String(entry.amount), userId, entry.fileName, entry.fileUrl, reportId, stage);
          }
          changes.push({ id: entry.id, toStage: stage });
        }
        await tx.$executeRawUnsafe(`UPDATE petty_cash_expense_reports SET report_name=$1,workflow_version=workflow_version+1,
          review_history=review_history || $2::jsonb,updated_at=CURRENT_TIMESTAMP WHERE id=$3`, reportName, JSON.stringify([{ userId, action: "resubmitted", changes, at: new Date().toISOString() }]), reportId);
      });
      return json({ ok: true, item: { id: reportId } });
    }
    if (body.action === "update") {
      const projectId = Number(body.projectId), expenseDate = String(body.expenseDate || "").trim(), description = String(body.description || "").trim(), budgetCode = String(body.budgetCode || "").trim(), amount = asAmount(body.amount);
      const fileName = String(body.fileName || "").trim().slice(0, 180) || null;
      const fileUrl = String(body.fileUrl || "").trim() || null;
      if (fileUrl && !/^\/uploads\/petty-cash-expenses\/[a-f0-9-]+\.[a-z0-9]+$/.test(fileUrl)) return json({ error: "invalid_attachment" }, 400);
      if (!id || !projectId || !expenseDate || !description || !budgetCode || amount <= 0n) return json({ error: "invalid_input" }, 400);
      const changed = await prisma.$executeRawUnsafe("UPDATE petty_cash_expenses SET expense_date=$1,description=$2,budget_code=$3,amount=$4::bigint,file_name=$8,file_url=$9,updated_at=CURRENT_TIMESTAMP WHERE id=$5 AND project_id=$6 AND created_by_id=$7 AND stage='planning' AND expense_report_id IS NULL", expenseDate, description, budgetCode, String(amount), id, projectId, userId, fileName, fileUrl);
      if (!changed) return json({ error: "not_allowed" }, 403);
      return json({ ok: true });
    }
    const decision = body.decision;
    if (!id || !["approve", "reject"].includes(decision)) return json({ error: "invalid_input" }, 400);
    const expenseRows = await prisma.$queryRawUnsafe("SELECT * FROM petty_cash_expenses WHERE id=$1", id);
    const expense = expenseRows[0];
    if (!expense) return json({ error: "not_found" }, 404);
    if (expense.expense_report_id) return json({ error: "not_allowed" }, 403);

    if (expense.stage === "planning") {
      if (!(await isMember(userId, "planning"))) return json({ error: "not_allowed" }, 403);
      if (decision === "reject") {
        await prisma.$executeRawUnsafe("UPDATE petty_cash_expenses SET stage='rejected',planning_status='rejected',planning_by_id=$1,planning_at=CURRENT_TIMESTAMP,rejected_by_id=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2", userId, id);
      } else {
        const managerId = Number(body.projectManagerId);
        const managers = await workflowMembers("project_manager");
        if (!managerId || !managers.some((user) => user.id === managerId)) return json({ error: "invalid_project_manager" }, 400);
        await prisma.$executeRawUnsafe("UPDATE petty_cash_expenses SET stage='project_manager',planning_status='approved',planning_by_id=$1,planning_at=CURRENT_TIMESTAMP,project_manager_id=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3", userId, managerId, id);
      }
      return json({ ok: true });
    }

    if (expense.stage === "project_manager") {
      if (Number(expense.project_manager_id) !== userId) return json({ error: "not_allowed" }, 403);
      const nextStage = decision === "approve" ? "completed" : "rejected";
      const managerStatus = decision === "approve" ? "approved" : "rejected";
      if (decision === "approve") {
        await prisma.$executeRawUnsafe("UPDATE petty_cash_expenses SET stage=$1,project_manager_status=$2,project_manager_by_id=$3,project_manager_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$4", nextStage, managerStatus, userId, id);
      } else {
        await prisma.$executeRawUnsafe("UPDATE petty_cash_expenses SET stage=$1,project_manager_status=$2,project_manager_by_id=$3,project_manager_at=CURRENT_TIMESTAMP,rejected_by_id=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$4", nextStage, managerStatus, userId, id);
      }
      return json({ ok: true });
    }
    return json({ error: "already_processed" }, 400);
  } catch (error) {
    console.error("petty_cash_expenses_patch_error", error);
    if (error instanceof RouteError) return json({ error: error.code }, error.status);
    return json({ error: "internal_error" }, 500);
  }
}

export async function DELETE(request) {
  try {
    await ensureTable();
    const userId = await userIdOf(request);
    if (!userId) return json({ error: "unauthorized" }, 401);
    const body = await request.json().catch(() => ({}));
    if (body.action === "clear_petty_cash_page_data") {
      // This action is deliberately scoped to the petty-cash tables and the
      // current user's records.  In particular, it never changes
      // tenkhah_requests or any other payment-request data.
      const result = await prisma.$transaction(async (tx) => {
        const expenses = await tx.$queryRawUnsafe(
          "SELECT id FROM petty_cash_expenses WHERE created_by_id=$1 AND expense_report_id IS NULL",
          userId,
        );
        const reports = await tx.$queryRawUnsafe(
          "SELECT id FROM petty_cash_settlement_reports WHERE created_by_id=$1",
          userId,
        );
        const expenseIds = expenses.map((row) => Number(row.id));
        const reportIds = reports.map((row) => Number(row.id));
        if (expenseIds.length || reportIds.length) {
          await tx.$executeRawUnsafe(
            "DELETE FROM petty_cash_settlement_report_items WHERE expense_id=ANY($1::int[]) OR report_id=ANY($2::int[])",
            expenseIds,
            reportIds,
          );
        }
        if (reportIds.length) await tx.$executeRawUnsafe("DELETE FROM petty_cash_settlement_reports WHERE id=ANY($1::int[])", reportIds);
        if (expenseIds.length) await tx.$executeRawUnsafe("DELETE FROM petty_cash_expenses WHERE id=ANY($1::int[])", expenseIds);
        return { expenses: expenseIds.length, reports: reportIds.length };
      });
      return json({ ok: true, deleted: result });
    }
    const ids = [...new Set((Array.isArray(body.ids) ? body.ids : []).map(Number).filter((id) => Number.isInteger(id) && id > 0))];
    if (!ids.length) return json({ error: "invalid_input" }, 400);
    const deleted = await prisma.$executeRawUnsafe("DELETE FROM petty_cash_expenses WHERE id=ANY($1::int[]) AND created_by_id=$2 AND stage='planning' AND expense_report_id IS NULL", ids, userId);
    if (!deleted) return json({ error: "not_allowed" }, 403);
    return json({ ok: true, deleted: Number(deleted) });
  } catch (error) {
    console.error("petty_cash_expenses_delete_error", error);
    return json({ error: "internal_error" }, 500);
  }
}
