import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
export const runtime = "nodejs";
let ready;
const allowed = new Set(["document", "liquidity"]);
const category = (request) => new URL(request.url).searchParams.get("category") || "";
async function ensure() { if (!ready) ready = prisma.$executeRawUnsafe("CREATE TABLE IF NOT EXISTS financial_base_options (id SERIAL PRIMARY KEY, category VARCHAR(20) NOT NULL, title TEXT NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(category,title))"); return ready; }
export async function GET(request) { try { await ensure(); const c = category(request); if (!allowed.has(c)) return NextResponse.json({ error: "invalid_category" }, { status: 400 }); const items = await prisma.$queryRawUnsafe("SELECT id,title FROM financial_base_options WHERE category=$1 ORDER BY id", c); return NextResponse.json({ items }); } catch { return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
export async function POST(request) { try { await ensure(); const c = category(request), title = String((await request.json()).title || "").trim(); if (!allowed.has(c) || !title) return NextResponse.json({ error: "invalid_input" }, { status: 400 }); const rows = await prisma.$queryRawUnsafe("INSERT INTO financial_base_options(category,title) VALUES($1,$2) RETURNING id,title", c, title); return NextResponse.json({ item: rows[0] }, { status: 201 }); } catch (e) { return NextResponse.json({ error: e?.code === "23505" ? "title_exists" : "internal_error" }, { status: e?.code === "23505" ? 409 : 500 }); } }
export async function PATCH(request) { try { await ensure(); const c = category(request), b = await request.json(), id = Number(b.id), title = String(b.title || "").trim(); if (!allowed.has(c) || !Number.isInteger(id) || !title) return NextResponse.json({ error: "invalid_input" }, { status: 400 }); const rows = await prisma.$queryRawUnsafe("UPDATE financial_base_options SET title=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND category=$3 RETURNING id,title", title, id, c); return rows[0] ? NextResponse.json({ item: rows[0] }) : NextResponse.json({ error: "not_found" }, { status: 404 }); } catch { return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
export async function DELETE(request) { try { await ensure(); const c = category(request), ids = Array.from(new Set((await request.json()).ids?.map(Number).filter(Number.isInteger) || [])); if (!allowed.has(c) || !ids.length) return NextResponse.json({ error: "invalid_input" }, { status: 400 }); await prisma.$executeRawUnsafe("DELETE FROM financial_base_options WHERE category=$1 AND id=ANY($2::int[])", c, ids); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "internal_error" }, { status: 500 }); } }
